const addSkillsData = async (dbClient) => {
  const formateQuery = (data) => {
    return {
      text: 'INSERT INTO skills (id, course_id, subject_id, topic_id, name, description, points) VALUES($1, $2, $3, $4, $5, $6, $7);',
      values: [data.id, data.course_id, data.subject_id, data.topic_id, data.name, data.description, data.points],
    };
  };

  skills_data = [
    {
      id: 1,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Whole numbers, Rational Numbers',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 2,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Fractions, Decimals, and Percents',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 3,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Properties and Relationships',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 4,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Math Facts',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 5,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Addition and Subtraction',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 6,
      course_id: 1,
      subject_id: 6,
      topic_id: 1,
      name: 'Multiplication and Division',
      description: 'missing description',
      points: 3572,
    },
    {
      id: 8,
      course_id: 1,
      subject_id: 6,
      topic_id: 2,
      name: 'Patterns',
      description: 'missing description',
      points: 6250,
    },
    {
      id: 9,
      course_id: 1,
      subject_id: 6,
      topic_id: 2,
      name: 'Variable and Expressions',
      description: 'missing description',
      points: 6250,
    },
    {
      id: 10,
      course_id: 1,
      subject_id: 6,
      topic_id: 2,
      name: 'Equalities and Inequalities',
      description: 'missing description',
      points: 6250,
    }
    {
      id: 12,
      course_id: 1,
      subject_id: 6,
      topic_id: 3,
      name: 'Data Collection and Organization',
      description: 'missing description',
      points: 6250,
    },
    {
      id: 13,
      course_id: 1,
      subject_id: 6,
      topic_id: 3,
      name: 'Data Visualization',
      description: 'missing description',
      points: 6250,
    },
    {
      id: 15,
      course_id: 1,
      subject_id: 6,
      topic_id: 3,
      name: 'Probability',
      description: 'missing description',
      points: 6250,
    },
    {
      id: 16,
      course_id: 1,
      subject_id: 6,
      topic_id: 4,
      name: 'Geometric Reasoning',
      description: 'missing description',
      points: 5000,
    },
    {
      id: 17,
      course_id: 1,
      subject_id: 6,
      topic_id: 4,
      name: 'Location & Movement',
      description: 'missing description',
      points: 5000,
    },
    {
      id: 18,
      course_id: 1,
      subject_id: 6,
      topic_id: 4,
      name: 'The Metric System',
      description: 'missing description',
      points: 5000,
    },
    {
      id: 19,
      course_id: 1,
      subject_id: 6,
      topic_id: 4,
      name: 'Angles',
      description: 'missing description',
      points: 5000,
    },
    {
      id: 20,
      course_id: 1,
      subject_id: 6,
      topic_id: 4,
      name: 'Area and Surface Area',
      description: 'missing description',
      points: 5000,
    },
    {
      id: 21,
      course_id: 1,
      subject_id: 6,
      topic_id: 5,
      name: 'Money Concept',
      description: 'missing description',
      points: 8334,
    },
    {
      id: 22,
      course_id: 1,
      subject_id: 6,
      topic_id: 5,
      name: 'Financial Management',
      description: 'missing description',
      points: 8334,
    },
    {
      id: 23,
      course_id: 1,
      subject_id: 6,
      topic_id: 5,
      name: 'Consumer and Civic Awareness',
      description: 'missing description',
      points: 8334,
    },
  ];

  for (let i = 0; i < skills_data.length; i++) {
    await dbClient.query(formateQuery(skills_data[i])).then((success) => {
      console.log(`4- Skills data: ${i + 1} of ${skills_data.length}`);
    });
  }
};

module.exports = addSkillsData;
